// Generated by Apple Swift version 2.0 (swiftlang-700.0.59 clang-700.0.72)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import SpriteKit;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface SKNode (SWIFT_EXTENSION(TWSpriteKitUtils))
- (void)removeNodeFromCollection:(BOOL)withRefresh;
@end


@interface SKShapeNode (SWIFT_EXTENSION(TWSpriteKitUtils))
@end

@class NSCoder;
@class SKTexture;
@class SKLabelNode;
@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC16TWSpriteKitUtils9TWControl")
@interface TWControl : SKNode
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// <ul><li>Initializes a general TWControl of type .Texture with a single highlighted texture possibility</li></ul>
- (nonnull instancetype)initWithNormalTexture:(SKTexture * __nonnull)normalTexture selectedTexture:(SKTexture * __nullable)selectedTexture singleHighlightedTexture:(SKTexture * __nullable)singleHighlightedTexture disabledTexture:(SKTexture * __nullable)disabledTexture OBJC_DESIGNATED_INITIALIZER;

/// <ul><li>Initializes a general TWControl of type .Color with a single highlighted color possibility</li></ul>
- (nonnull instancetype)initWithSize:(CGSize)size normalColor:(UIColor * __nonnull)normalColor selectedColor:(UIColor * __nullable)selectedColor singleHighlightedColor:(UIColor * __nullable)singleHighlightedColor disabledColor:(UIColor * __nullable)disabledColor OBJC_DESIGNATED_INITIALIZER;

/// <ul><li>Initializes a general TWControl of type .Text with multiple highlighted color possibility</li></ul>
- (nonnull instancetype)initWithNormalText:(NSString * __nonnull)normalText selectedText:(NSString * __nullable)selectedText singleHighlightedText:(NSString * __nullable)singleHighlightedText disabledText:(NSString * __nullable)disabledText OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) CGSize size;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL selected;
@property (nonatomic) BOOL highlighted;
@property (nonatomic, getter=isUserInteractionEnabled) BOOL userInteractionEnabled;
@property (nonatomic, readonly) SKNode * __nonnull genericNode;
@property (nonatomic) BOOL soundEffectsEnabled;
+ (NSString * __nullable)defaultTouchDownSoundFileName;
+ (void)setDefaultTouchDownSoundFileName:(NSString * __nullable)newValue;
+ (NSString * __nullable)defaultTouchUpSoundFileName;
+ (void)setDefaultTouchUpSoundFileName:(NSString * __nullable)newValue;
+ (NSString * __nullable)defaultDisabledTouchDownFileName;
+ (void)setDefaultDisabledTouchDownFileName:(NSString * __nullable)newValue;
@property (nonatomic, copy) NSString * __nullable touchDownSoundFileName;
@property (nonatomic, copy) NSString * __nullable touchUpSoundFileName;
@property (nonatomic, copy) NSString * __nullable disabledTouchDownFileName;
@property (nonatomic) UIColor * __null_unspecified normalStateColor;
@property (nonatomic) UIColor * __nullable selectedStateColor;
@property (nonatomic) UIColor * __nullable disabledStateColor;
@property (nonatomic) UIColor * __nullable highlightedStateSingleColor;
@property (nonatomic) UIColor * __nullable highlightedStateMultiColorFromNormal;
@property (nonatomic) UIColor * __nullable highlightedStateMultiColorFromSelected;
@property (nonatomic) SKTexture * __null_unspecified normalStateTexture;
@property (nonatomic) SKTexture * __nullable selectedStateTexture;
@property (nonatomic) SKTexture * __nullable disabledStateTexture;
@property (nonatomic) SKTexture * __nullable highlightedStateSingleTexture;
@property (nonatomic) SKTexture * __nullable highlightedStateMultiTextureFromNormal;
@property (nonatomic) SKTexture * __nullable highlightedStateMultiTextureFromSelected;
@property (nonatomic) SKLabelNode * __nullable normalStateLabel;
@property (nonatomic) SKLabelNode * __nullable selectedStateLabel;
@property (nonatomic) SKLabelNode * __nullable disabledStateLabel;
@property (nonatomic) SKLabelNode * __nullable highlightedStateSingleLabel;
@property (nonatomic) SKLabelNode * __nullable highlightedStateMultiLabelFromNormal;
@property (nonatomic) SKLabelNode * __nullable highlightedStateMultiLabelFromSelected;
- (void)setNormalStateLabelText:(NSString * __nullable)text;
- (void)setSelectedStateLabelText:(NSString * __nullable)text;
- (void)setDisabledStateLabelText:(NSString * __nullable)text;
- (void)setHighlightedStateSingleLabelText:(NSString * __nullable)text;
- (void)setHighlightedStateMultiLabelTextFromNormal:(NSString * __nullable)text;
- (void)setHighlightedStateMultiLabelTextFromSelected:(NSString * __nullable)text;
- (void)setAllStatesLabelFontSize:(CGFloat)size;
- (void)setAllStatesLabelFontName:(NSString * __nonnull)fontName;
- (void)setNormalStateLabelFontColor:(UIColor * __nonnull)color;
- (void)setSelectedStateLabelFontColor:(UIColor * __nonnull)color;
- (void)setDisabledStateLabelFontColor:(UIColor * __nonnull)color;
- (void)setHighlightedStateSingleLabelFontColor:(UIColor * __nonnull)color;
- (void)setHighlightedStateMultiLabelFontColorFromNormal:(UIColor * __nonnull)color;
- (void)setHighlightedStateMultiLabelFontColorFromSelected:(UIColor * __nonnull)color;
- (void)setAllStatesLabelFontColor:(UIColor * __nonnull)color;
+ (CGPoint)defaultNormalStateLabelPosition;
+ (void)setDefaultNormalStateLabelPosition:(CGPoint)value;
+ (CGPoint)defaultSelectedStateLabelPosition;
+ (void)setDefaultSelectedStateLabelPosition:(CGPoint)value;
+ (CGPoint)defaultDisabledStateLabelPosition;
+ (void)setDefaultDisabledStateLabelPosition:(CGPoint)value;
+ (CGPoint)defaultHighlightedStateSingleLabelPosition;
+ (void)setDefaultHighlightedStateSingleLabelPosition:(CGPoint)value;
+ (CGPoint)defaultHighlightedStateMultiLabelPositionFromNormal;
+ (void)setDefaultHighlightedStateMultiLabelPositionFromNormal:(CGPoint)value;
+ (CGPoint)defaultHighlightedStateMultiLabelPositionFromSelected;
+ (void)setDefaultHighlightedStateMultiLabelPositionFromSelected:(CGPoint)value;
+ (void)setAllDefaultStatesLabelPosition:(CGPoint)pos;
@property (nonatomic) CGPoint normalStateLabelPosition;
@property (nonatomic) CGPoint selectedStateLabelPosition;
@property (nonatomic) CGPoint disabledStateLabelPosition;
@property (nonatomic) CGPoint highlightedStateSingleLabelPosition;
@property (nonatomic) CGPoint highlightedStateMultiLabelPositionFromNormal;
@property (nonatomic) CGPoint highlightedStateMultiLabelPositionFromSelected;
- (void)setAllStatesLabelPosition:(CGPoint)pos;
- (void)touchUpInside;
- (void)touchesBegan:(NSSet<UITouch *> * __nonnull)touches withEvent:(UIEvent * __nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * __nonnull)touches withEvent:(UIEvent * __nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * __nonnull)touches withEvent:(UIEvent * __nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * __nullable)touches withEvent:(UIEvent * __nullable)event;
@end


SWIFT_CLASS("_TtC16TWSpriteKitUtils8TWButton")
@interface TWButton : TWControl
- (nonnull instancetype)initWithNormalText:(NSString * __nonnull)normalText highlightedText:(NSString * __nullable)highlightedText;
- (nonnull instancetype)initWithNormalTexture:(SKTexture * __nonnull)normalTexture highlightedTexture:(SKTexture * __nullable)highlightedTexture;
- (nonnull instancetype)initWithSize:(CGSize)size normalColor:(UIColor * __nonnull)normalColor highlightedColor:(UIColor * __nullable)highlightedColor;
- (void)touchUpInside;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNormalTexture:(SKTexture * __nonnull)normalTexture selectedTexture:(SKTexture * __nullable)selectedTexture singleHighlightedTexture:(SKTexture * __nullable)singleHighlightedTexture disabledTexture:(SKTexture * __nullable)disabledTexture OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSize:(CGSize)size normalColor:(UIColor * __nonnull)normalColor selectedColor:(UIColor * __nullable)selectedColor singleHighlightedColor:(UIColor * __nullable)singleHighlightedColor disabledColor:(UIColor * __nullable)disabledColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNormalText:(NSString * __nonnull)normalText selectedText:(NSString * __nullable)selectedText singleHighlightedText:(NSString * __nullable)singleHighlightedText disabledText:(NSString * __nullable)disabledText OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC16TWSpriteKitUtils16TWCollectionNode")
@interface TWCollectionNode : SKSpriteNode
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)reloadCollection;
- (void)addNode:(SKNode * __nonnull)node reload:(BOOL)reload;
@end



@interface TWControl (SWIFT_EXTENSION(TWSpriteKitUtils))
@end


@interface TWControl (SWIFT_EXTENSION(TWSpriteKitUtils))
@end


SWIFT_CLASS("_TtC16TWSpriteKitUtils11TWStackNode")
@interface TWStackNode : SKSpriteNode
@property (nonatomic) BOOL automaticSpacing;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)reloadStack;
- (void)addNode:(SKNode * __nonnull)node reload:(BOOL)reload;
- (void)removeNode:(SKNode * __nonnull)node reload:(BOOL)reload;
@end


SWIFT_CLASS("_TtC16TWSpriteKitUtils8TWSwitch")
@interface TWSwitch : TWControl
- (nonnull instancetype)initWithNormalText:(NSString * __nonnull)normalText selectedText:(NSString * __nullable)selectedText;
- (nonnull instancetype)initWithNormalTexture:(SKTexture * __nonnull)normalTexture selectedTexture:(SKTexture * __nullable)selectedTexture;
- (nonnull instancetype)initWithSize:(CGSize)size normalColor:(UIColor * __nonnull)normalColor selectedColor:(UIColor * __nullable)selectedColor;
@property (nonatomic) BOOL selected;
- (void)touchUpInside;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNormalTexture:(SKTexture * __nonnull)normalTexture selectedTexture:(SKTexture * __nullable)selectedTexture singleHighlightedTexture:(SKTexture * __nullable)singleHighlightedTexture disabledTexture:(SKTexture * __nullable)disabledTexture OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSize:(CGSize)size normalColor:(UIColor * __nonnull)normalColor selectedColor:(UIColor * __nullable)selectedColor singleHighlightedColor:(UIColor * __nullable)singleHighlightedColor disabledColor:(UIColor * __nullable)disabledColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNormalText:(NSString * __nonnull)normalText selectedText:(NSString * __nullable)selectedText singleHighlightedText:(NSString * __nullable)singleHighlightedText disabledText:(NSString * __nullable)disabledText OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
